sudo: false
language: erlang
otp_release:
  - R16B03-1
  - 17.5
  - 18.1
  - 19.1
env:
  global:
  - MAIN_OTP=19.1
  matrix:
  - FORCE_REBAR2=true
  - FORCE_REBAR2=false PATH=$PATH:$PWD
branches:
  only:
    - master
    - /^[0-9]+\.[0-9]+\.[0-9]+/
install:
  - make travis-install
script:
  - make check_warnings
  - make eunit
deploy:
  skip_cleanup: true
  provider: script
  script: make travis-publish
  on:
    tags: true
    condition: $FORCE_REBAR2 = false && $TRAVIS_OTP_RELEASE = $MAIN_OTP
